//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPost()
        {
            this.tblPosts1 = new HashSet<tblPost>();
            this.tblUsersThatLikedPosts = new HashSet<tblUsersThatLikedPost>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTimeOfPosting { get; set; }
        public string Content { get; set; }
        public Nullable<int> NumberOfLikes { get; set; }
        public Nullable<int> FKUserThatPosted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPost> tblPosts1 { get; set; }
        public virtual tblPost tblPost1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersThatLikedPost> tblUsersThatLikedPosts { get; set; }
    }
}
